---
title: "Wild type post division comparison"
output: html_notebook
---


```{r include=FALSE}
library(readxl)
library(tidyverse)
```


```{r}
expdf<-read_excel("exp_data.xlsx")
expdf$ori="exp"


#Power law model
fndiv<-function(x,ss,ns){
  return(sum(log2(x/ss)+rnorm(1,mean=0,sd=ns)>c(0,1,2,3,4,5)))
}
ndiv<-apply(X=expdf[,1],MARGIN=1,FUN=fndiv,169.9798,0.7)
pldf<-data.frame(vol=expdf$vol,ndiv=ndiv)
pldf$ori<-"p2"

#3 parameter model
fndiv<-function(x,ss,ns,z0){
  return(sum(log2(x/ss)+rnorm(1,mean=0,sd=ns)>c(z0,1,2,3,4,5)))
}
ndiv<-apply(X=expdf[,1],MARGIN=1,FUN=fndiv,146.6105, 0.3111578, 0.7004869)
p3df<-data.frame(vol=expdf$vol,ndiv=ndiv)
p3df$ori<-"p3"

#7 parameter model
fndiv<-function(x,ss,ns,z0,z1,z2,z3,z4){
  return(sum(log2(x/ss)+rnorm(1,mean=0,sd=ns)>c(z0,z1,z2,z3,z4)))
}
ndiv<-apply(X=expdf[,1],MARGIN=1,FUN=fndiv,141.78, 0.31, 0.73,1.01,2.16,3.03,4)
p7df<-data.frame(vol=expdf$vol,ndiv=ndiv)
p7df$ori<-"p7"

cmpdf<-rbind(expdf,pldf,p3df,p7df)

#computing daugther sizes
cmpdf$daup<-cmpdf$vol/2^cmpdf$ndiv
cmpdf$daup[cmpdf$ndiv>0]<-cmpdf$daup[cmpdf$ndiv>0]*0.75

```



Plots

```{r}
ggplot(cmpdf,aes(x=daup,fill=ori))+geom_density(alpha=0.4)+scale_x_log10()
```
```{r fig.height=3, fig.width=10}
ggplot(cmpdf%>%filter(ndiv>0)%>%arrange(),aes(x=daup,color=ori,linetype=ori))+
  geom_density(size=2)+
  #scale_colour_manual(breaks = c("exp","p2","p3"),values = c("black","#619CFF","#F8766D"))+
  scale_x_log10(limits=c(20,500))+
  #scale_linetype_manual(breaks = c("exp","p2","p3"), values=c("dotted","dashed","solid"))+
  theme_classic()

ggsave("wt_dg_cmp.png",width = 10,height = 3)
```
```{r}
cmpdf%>%
  filter(ndiv>0)%>%
  group_by(ori)%>%
  summarise(md=mean(daup),sdd=sqrt(var(daup)),mdn=median(daup))%>%
  mutate(cv=sdd/md)
```


```{r}

ggplot(cmpdf)+
  geom_histogram(aes(x=as.factor(ndiv),fill=as.factor(ori)),stat = "count",position = "dodge")

ggplot(cmpdf)+
  geom_histogram(aes(y=as.factor(ndiv),fill=as.factor(ori)),stat = "count",position = "dodge")

```



